sudo: required
services:
  - docker

before_install:
  - docker build -t lgxkevin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lgxkevin/react-test npm test -- --coverage

after_success:
  - docker build -t lgxkevin/multi-client ./client
  - docker build -t lgxkevin/multi-nginx ./nginx
  - docker build -t lgxkevin/multi-server ./server
  # - docker build -t lgxkevin/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lgxkevin/multi-client
  - docker push lgxkevin/multi-nginx
  - docker push lgxkevin/multi-server
  # - docker push lgxkevin/multi-worker

#access_key_id:
  #secure: $AWS_ACCESS_KEY
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: kevin-blog
  env: KevinBlog-env
  bucket_name: elasticbeanstalk-us-east-2-004804005847
  bucket_path: kevin-blog
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
