version: '3'
services: 
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
  # redis:
  #   image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  # server service
  api:
    build:
      dockerfile: Dockerfile.dev
      # specify the exact directory that used to build image out
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    depends_on:
      - mongo
  # Client service
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  # worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379